version: "3"

services:
  db:
    image: mysql
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes: 
  db:
  